@extends('layouts.app')

@section('content')
    <h3 class="mb-3">Terms of service</h3>

    <ol class="text-justify">
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In quam nisl, aliquam at ex a, convallis malesuada mi. Fusce eget ante eget est efficitur ultrices. Nullam imperdiet dapibus erat vitae pellentesque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce quis sollicitudin velit. Ut quis nunc rhoncus, consectetur tellus aliquet, malesuada risus. In imperdiet, nunc eu ultricies volutpat, eros augue consectetur augue, a tincidunt quam massa nec nisi. Maecenas convallis leo eu libero vestibulum, non varius justo varius. Curabitur blandit, ipsum at tempus vulputate, lorem nisi blandit ex, quis tincidunt nisi ante eget lectus. In elementum sapien quis pellentesque vehicula. Mauris et vulputate tortor. Ut vel risus urna. Curabitur id justo nisl. Aenean iaculis erat nisi, sit amet laoreet est viverra sed.</li>

        <li>Vestibulum quis lacinia enim. Phasellus tempus porttitor euismod. Quisque vestibulum in massa sit amet aliquet. Ut porttitor turpis non sem ullamcorper rhoncus. Suspendisse scelerisque massa vitae justo placerat blandit. Integer vestibulum a massa sit amet consectetur. Phasellus efficitur odio arcu, mattis aliquam mauris vestibulum nec. Proin malesuada mollis magna, auctor vulputate quam tempor at. Duis malesuada diam ac nisl lobortis rhoncus a sed dolor. Phasellus vitae purus lobortis, venenatis est sit amet, facilisis nibh. Nunc laoreet, elit ac fringilla fringilla, mi metus fermentum sapien, non tempor justo erat id dolor.</li>

        <li>Aenean vulputate, eros eu vehicula molestie, lorem nisl mattis arcu, id lobortis eros magna vel arcu. Donec in eleifend mi. Duis ac velit id mauris facilisis volutpat. Nunc hendrerit, tortor a maximus fringilla, enim velit vehicula leo, sed convallis erat leo id diam. Aenean cursus justo nec arcu pretium, quis lobortis eros dictum. Maecenas vel sem ut orci dignissim elementum. Curabitur a sodales ante.</li>

        <li>Nullam suscipit quis nisi in varius. Vestibulum mollis erat at varius tempus. Ut ut auctor massa. Proin viverra rutrum tellus vel vulputate. Suspendisse et maximus tortor. Nullam sit amet eros fringilla, accumsan urna nec, bibendum magna. Morbi sit amet urna tincidunt, consequat lacus ut, dictum tortor. Nam nec ullamcorper massa. Mauris vel nisi quis ante cursus blandit quis nec eros. Nunc semper ante vitae lacus porta eleifend. Suspendisse egestas tortor a tempor rutrum. Sed consectetur mi vel lorem viverra, quis tempus orci egestas. Praesent urna enim, pretium eget ultricies eu, ornare eu lectus. In dignissim dictum diam, in aliquet neque congue blandit. Suspendisse et ex neque. Sed dapibus blandit lacus, non facilisis lorem luctus sit amet.</li>

        <li>Praesent scelerisque sapien a tellus gravida, efficitur posuere lorem varius. In mattis interdum luctus. Fusce convallis nunc non aliquam porta. Cras lobortis hendrerit nisi, sed consectetur mi auctor quis. Sed ut ante dui. Morbi tristique nisi eu porttitor sollicitudin. Sed sit amet felis eget diam maximus dapibus quis eu felis. Nulla at tortor vehicula, iaculis quam eu, vehicula lacus. Vestibulum vehicula dolor mauris, fringilla iaculis tortor tempor feugiat. Integer pellentesque est ac mauris pretium finibus.</li>

        <li>Maecenas pellentesque blandit diam, a aliquet magna dignissim consequat. Nullam condimentum nisl enim, nec malesuada odio sollicitudin quis. Sed quam augue, rutrum ut ex non, ullamcorper vehicula ligula. Fusce non justo quis orci sodales efficitur. Curabitur ultrices varius massa ut sagittis. Vestibulum arcu ligula, congue non mi eget, euismod consequat tortor. Sed at tellus blandit, pretium justo eget, dignissim neque. Etiam auctor bibendum auctor. In efficitur eros quis imperdiet maximus. Donec consequat malesuada ante vitae mattis. Phasellus tempor nibh et purus porta, id scelerisque nibh tincidunt.</li>

        <li>Integer ultricies varius lacus, sed ornare nulla sagittis nec. Aenean iaculis fermentum tempus. Aenean quis sapien in sapien euismod pharetra. Aliquam vitae purus luctus mi eleifend fringilla. Aenean eu lorem porttitor, gravida tellus sed, mollis est. Quisque et aliquet odio. Etiam sed varius arcu. Aenean purus sem, dapibus in feugiat at, rhoncus in mi. Etiam id lacinia nulla. Nunc elementum iaculis metus nec condimentum. Etiam fermentum turpis nulla, non elementum ex pretium sit amet. Donec dapibus a turpis vitae volutpat. Integer neque lorem, faucibus et felis vitae, elementum pulvinar magna. Maecenas id metus quis lacus sagittis pulvinar sed quis elit.</li>

        <li>Ut ultrices arcu et facilisis pharetra. Mauris eros urna, fermentum fermentum faucibus nec, rhoncus quis tortor. Donec accumsan molestie dapibus. Integer tortor nibh, faucibus vel fermentum eu, pharetra at mauris. Donec sit amet dignissim ipsum. Vivamus ac quam tempor, efficitur magna vel, viverra orci. Praesent rhoncus erat ut augue suscipit, non molestie ligula elementum. Integer at posuere justo, feugiat dapibus dui. Nam id sagittis leo. Aliquam imperdiet finibus lacinia. Suspendisse lorem nibh, consequat ut ante ac, tempus finibus elit. Praesent commodo mi at purus facilisis varius. In vitae augue leo.</li>

        <li>Sed pharetra magna quis ex scelerisque, eget porttitor dui finibus. Donec eros nunc, pulvinar in nisi in, ultrices porta eros. Vestibulum euismod quam quis ex volutpat, vel venenatis nisi sodales. Integer hendrerit sed ligula id pulvinar. Cras quis odio augue. Donec vel nisi maximus, finibus leo eget, scelerisque risus. Vestibulum et lacus sagittis, lacinia dolor non, imperdiet nulla. Sed egestas pellentesque dolor eget accumsan. Phasellus ultrices orci ut lacinia sodales. Nulla facilisi.</li>

        <li>Nunc feugiat metus nec condimentum tincidunt. Vivamus ut eleifend eros. Praesent nec mauris id orci egestas aliquet. Sed nibh tortor, fermentum eu lacinia sit amet, dignissim ac risus. Proin porttitor, nisi ornare pretium pretium, lacus turpis feugiat massa, ac semper odio odio quis dui. Nullam turpis risus, sagittis elementum massa non, fringilla elementum nisl. Donec vitae pellentesque risus, sed fermentum turpis. Donec nec faucibus nisi. Nullam non purus erat. Nunc elementum tortor sit amet consectetur scelerisque. Nam porta, ante ac posuere rhoncus, metus sem viverra dui, vel sagittis metus dui ut ante. Aenean aliquet consectetur purus eu posuere. Integer et dolor a nisi posuere pulvinar. Aenean non tempor eros. Praesent id enim vel mauris euismod porttitor eu ac augue. Curabitur eu imperdiet nisi, at consectetur velit.</li>
    </ol>
@endsection
